In [1]:
import numpy as np
import random

#### Fitness Function

In [18]:
def fitness(np):
    f=0
    f=np[0]+(np[1]*2)+(np[2]*3)+(np[3]*4)-30
    return f

In [19]:
pop_size=6
ch_size=4
min_value=0
max_value=30
pc=0.4 #Crossover Rate
pm = 0.1 #Mutation Rate

#### Initialization

In [20]:
chromosomes = np.random.randint(min_value,max_value,size=(pop_size,ch_size))
print(chromosomes)

[[ 3  0  4  8]
 [ 4 15 22 26]
 [ 7 23 19 27]
 [ 2 28 16 25]
 [ 0 24 15 12]
 [ 8  7 28 11]]


#### Fitness Evaluation

In [21]:
f=np.zeros(pop_size,dtype='int16')
#fit=[]
for i in range(0,6):
    #fit.append(fitness(ini[i]))
    f[i]=fitness(chromosomes[i])
print(f)

[ 17 174 188 176 111 120]


In [6]:
inv_f = np.zeros(pop_size)
inv_f = 1/(f+1)
print(inv_f)

p=np.zeros(pop_size)
p = inv_f/np.sum(inv_f)
print(p)
print(np.sum(p))

c=np.zeros(pop_size)
for i in range(0,pop_size):
    c[i]=np.sum(p[:(i+1)])
print(c)
r=np.random.rand(pop_size)
print(r)

[0.04545455 0.01666667 0.01190476 0.03030303 0.01265823 0.02941176]
[0.310484   0.11384413 0.08131724 0.20698933 0.0864639  0.20090141]
1.0
[0.310484   0.42432813 0.50564536 0.71263469 0.79909859 1.        ]
[0.24377565 0.29618367 0.02125889 0.84994668 0.17032387 0.49135178]


In [7]:
new_chromosomes = np.zeros((pop_size,ch_size),dtype='int16')
for i in range(0,pop_size):
    for j in range(0,pop_size):
        if (r[i] <= c[j]):
            new_chromosomes[i]=chromosomes[j]
            break

chromosomes=np.copy(new_chromosomes)
print(new_chromosomes)

[[ 7  8  4  2]
 [ 7  8  4  2]
 [ 7  8  4  2]
 [ 1 15  1 16]
 [ 7  8  4  2]
 [19 23 27 14]]


#### Crossover

In [8]:
ch=[]
ch_position=[]
crossover_pt=[]
for i in range(0,pop_size):
    r = random.random()
    if(r<pc):
        ch.append(chromosomes[i])
        ch_position.append(i)
print(ch)   
print(ch_position)
crossover_pt=np.random.randint(1,(ch_size),size=len(ch))
print(crossover_pt)
ch[0][1:3]

[array([7, 8, 4, 2], dtype=int16), array([ 1, 15,  1, 16], dtype=int16), array([7, 8, 4, 2], dtype=int16)]
[2, 3, 4]
[1 1 1]


array([8, 4], dtype=int16)

In [9]:
new_ch=[]
for i in range(0,len(ch)):
    new_ch.append(np.copy(ch[i]))
    if(i<len(ch)-1):
        new_ch[i][crossover_pt[i]:]=ch[i+1][crossover_pt[i]:].copy()
    else:
        new_ch[i][crossover_pt[i]:]=ch[0][crossover_pt[i]:].copy()
print(new_ch)
ch=new_ch.copy()

[array([ 7, 15,  1, 16], dtype=int16), array([1, 8, 4, 2], dtype=int16), array([7, 8, 4, 2], dtype=int16)]


In [10]:
for i in range(0,len(ch)):
    chromosomes[ch_position[i]]=np.copy(ch[i])
print(chromosomes)

[[ 7  8  4  2]
 [ 7  8  4  2]
 [ 7 15  1 16]
 [ 1  8  4  2]
 [ 7  8  4  2]
 [19 23 27 14]]


#### Mutation

In [11]:
def chromesome_gene_pos(x):
    ch_pos=int(x/ch_size)
    gene_pos=x%ch_size
    return ch_pos,gene_pos

In [15]:
mutation_range = pop_size* ch_size*pm
mutation_range = int(mutation_range)
num_of_mut = random.randrange(0,mutation_range+1)
print(mutation_range)
print(num_of_mut)

2
2


In [16]:
mut_values=np.random.randint(min_value,max_value,size=num_of_mut)
mut_pos=np.random.randint(0,(pop_size*ch_size),size=num_of_mut)
print(mut_pos)
print(mut_values)
for i in range(0,num_of_mut):
    ch_pos,gene_pos=chromesome_gene_pos(mut_pos[i])
    print(ch_pos,gene_pos)
    chromosomes[ch_pos,gene_pos]=mut_values[i].copy()

[11  9]
[17 20]
2 3
2 1


In [17]:
print('Updated Chromosomes')
print(chromosomes)
for i in range(0,6):
    #fit.append(fitness(ini[i]))
    f[i]=fitness(chromosomes[i])
print(f)

Updated Chromosomes
[[ 7  8  4  2]
 [ 7  8  4  2]
 [ 7 20  1 17]
 [ 1  8  4  2]
 [ 7  8  4  2]
 [19 23 27 14]]
[21 21 45 15 21 83]
